name = "ai-images-pilot"
main = "src/index.js"
compatibility_date = "2025-05-01"

[ai]
binding = "AI"

[[d1_databases]]
binding = "DB"
database_name = "ai-images-db"
database_id = "2caa9097-c3b2-43f0-90b4-2db424b90fd6"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "ai-images"

[[vectorize]]
binding = "VECTORIZE"
index_name = "ai-images-index"

[[queues.producers]]
binding = "PROCESS_QUEUE"
queue = "ai-images-process"

[[queues.consumers]]
queue = "ai-images-process"
max_batch_size = 1
max_batch_timeout = 5
max_retries = 3
retry_delay = 30

[triggers]
crons = ["0 0 * * *"]
